CC := aarch64-linux-gnu-gcc

CFLAGS := -g -Wall $(shell aarch64-linux-gnu-pkg-config --cflags wayland-client)

LDFLAGS := $(shell aarch64-linux-gnu-pkg-config --libs wayland-client)

OUTPUT := wl-camera-shm

OBJS := main.o camera.o convert.o wayland.o util.o

.PHONY : all clean

all : $(OUTPUT)

$(OUTPUT) : $(OBJS)
	$(CC) -o $@ $^ $(LDFLAGS)

.c.o :
	$(CC) -o $@ -c $< $(CFLAGS)

clean :
	rm -f $(OUTPUT) $(OBJS)

